### ISSUE TITLE
支持 ipv6的 toa 在centos7.7下编译失败

### ISSUE THREAD

**Issue by snailq** [iqiyi/dpvs#504]
redhat-release:CentOS Linux release 7.7.1908 (Core)
kernel:3.10.0-1062.4.3.el7.x86_64

/tmp/toa-200-ipv6/toa.c:912:15: error: variable ‘toa_sockopts’ has initializer but incomplete type
 static struct nf_sockopt_ops toa_sockopts = {
               ^
/tmp/toa-200-ipv6/toa.c:913:5: error: unknown field ‘pf’ specified in initializer
     .pf    = PF_INET,
     ^
/tmp/toa-200-ipv6/toa.c:913:5: warning: excess elements in struct initializer [enabled by default]
/tmp/toa-200-ipv6/toa.c:913:5: warning: (near initialization for ‘toa_sockopts’) [enabled by default]
/tmp/toa-200-ipv6/toa.c:914:5: error: unknown field ‘owner’ specified in initializer
     .owner    = THIS_MODULE,
     ^
/tmp/toa-200-ipv6/toa.c:914:5: warning: excess elements in struct initializer [enabled by default]
/tmp/toa-200-ipv6/toa.c:914:5: warning: (near initialization for ‘toa_sockopts’) [enabled by default]
/tmp/toa-200-ipv6/toa.c:917:5: error: unknown field ‘get_optmin’ specified in initializer
     .get_optmin = TOA_BASE_CTL,
     ^
/tmp/toa-200-ipv6/toa.c:917:5: warning: excess elements in struct initializer [enabled by default]
/tmp/toa-200-ipv6/toa.c:917:5: warning: (near initialization for ‘toa_sockopts’) [enabled by default]
/tmp/toa-200-ipv6/toa.c:918:5: error: unknown field ‘get_optmax’ specified in initializer
     .get_optmax = TOA_SO_GET_MAX+1,
     ^
/tmp/toa-200-ipv6/toa.c:918:5: warning: excess elements in struct initializer [enabled by default]
/tmp/toa-200-ipv6/toa.c:918:5: warning: (near initialization for ‘toa_sockopts’) [enabled by default]
/tmp/toa-200-ipv6/toa.c:919:5: error: unknown field ‘get’ specified in initializer
     .get        = inet64_getname_toa,
     ^
/tmp/toa-200-ipv6/toa.c:919:5: warning: excess elements in struct initializer [enabled by default]
/tmp/toa-200-ipv6/toa.c:919:5: warning: (near initialization for ‘toa_sockopts’) [enabled by default]
/tmp/toa-200-ipv6/toa.c: In function ‘toa_init’:
/tmp/toa-200-ipv6/toa.c:979:5: error: implicit declaration of function ‘nf_register_sockopt’ [-Werror=implicit-function-declaration]
     if (0 != nf_register_sockopt(&toa_sockopts)) {
     ^
/tmp/toa-200-ipv6/toa.c: In function ‘toa_exit’:
/tmp/toa-200-ipv6/toa.c:1007:5: error: implicit declaration of function ‘nf_unregister_sockopt’ [-Werror=implicit-function-declaration]
     nf_unregister_sockopt(&toa_sockopts);

**Comment by ywc689** [comment]
Try the latest release. It should be fixed.

**Comment by liweitianux** [comment]
Well, I can confirm that the `kmod/toa` module is having the reported compilation issue on CentOS 7.8, but it compiles fine on CentOS 7.4.

Regards

**Comment by ywc689** [comment]
Can you try the latest codes in `devel` ?  It should have been fixed in commit 54fbdcc8e768f0b58851f4ba3934c2a04b3333d4. Release v1.8.4 don't have the commit.

**Comment by liweitianux** [comment]
@ywc689 , oh cool.  Sorry that I forgot about the `devel` branch.  I confirm that both toa/uoa modules on the `devel` branch compile OK on CentOS 7.8.

I'll also close my PR.  Thank you.
